Adding images in markdown: ![](path/to/file)
· Not ideal… difficult to control size/scale
· Better way to add images use R code!
· knitr package has include_graphics function
· Use knitr or code chunk options to control size/scale!
Ex:
```{r graphics, out.width = "800px", echo = FALSE}
knitr::include_graphics("path/to/file")
```
